"""Local disk storage. Development only.

Render replaces a service's disk on every deploy, so anything written here in
production would be lost; the settings refuse that combination.
"""

from __future__ import annotations

import re
from pathlib import Path

from app.storage.base import StoredFile

# Keys are generated by this application, never by a client. The pattern is
# enforced anyway, so no caller can talk this driver into writing outside its
# own directory.
SAFE_KEY = re.compile(r"^[0-9a-f]{32}\.(jpg|png|webp)$")


class LocalStorage:
    def __init__(self, directory: str | Path, public_base_url: str) -> None:
        self.directory = Path(directory).resolve()
        self.directory.mkdir(parents=True, exist_ok=True)
        self.public_base_url = public_base_url.rstrip("/")

    def _path(self, key: str) -> Path:
        if not SAFE_KEY.match(key):
            raise ValueError("Unsafe storage key.")
        return self.directory / key

    def save(self, data: bytes, *, key: str, content_type: str) -> StoredFile:
        self._path(key).write_bytes(data)
        return StoredFile(key=key, url=f"{self.public_base_url}/media/{key}")

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)
