"""article categories and articles

Revision ID: 1f3e986a697e
Revises: b4ad6af68e01
Create Date: 2026-09-22 13:31:04.539322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3e986a697e'
down_revision = 'b4ad6af68e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('article_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_categories_slug'), ['slug'], unique=True)

    op.create_table('articles',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='ck_articles_status', native_enum=False, length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('fixture_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('byline', sa.String(length=160), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'published' OR published_at IS NOT NULL", name='ck_articles_published_has_date'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['article_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=True)
        batch_op.create_index('ix_articles_status_published_at', ['status', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_team_id'))
        batch_op.drop_index('ix_articles_status_published_at')
        batch_op.drop_index(batch_op.f('ix_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_articles_fixture_id'))
        batch_op.drop_index(batch_op.f('ix_articles_category_id'))

    op.drop_table('articles')
    with op.batch_alter_table('article_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_categories_slug'))

    op.drop_table('article_categories')
    # ### end Alembic commands ###
