"""competition, fixture, event, statistic and standing tables

Revision ID: 406b36ded759
Revises: 46946a13c508
Create Date: 2026-09-18 07:53:56.040936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406b36ded759'
down_revision = '46946a13c508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('has_standings', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitions_slug'), ['slug'], unique=True)

    op.create_table('opponents',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('crest_url', sa.String(length=500), nullable=True),
    sa.Column('home_ground', sa.String(length=160), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('opponents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opponents_slug'), ['slug'], unique=True)

    op.create_table('seasons',
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'label', name='uq_seasons_comp_label')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seasons_slug'), ['slug'], unique=True)

    op.create_table('league_standings',
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('opponent_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(team_id IS NOT NULL AND opponent_id IS NULL) OR (team_id IS NULL AND opponent_id IS NOT NULL)', name='ck_standing_exactly_one_club'),
    sa.ForeignKeyConstraint(['opponent_id'], ['opponents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'position', name='uq_standing_season_position')
    )
    with op.batch_alter_table('league_standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_standings_season_id'), ['season_id'], unique=False)

    op.create_table('fixtures',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('opponent_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_on', sa.Date(), nullable=True),
    sa.Column('venue', sa.Enum('home', 'away', 'neutral', name='ck_fixtures_venue', native_enum=False, length=32), nullable=False),
    sa.Column('venue_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'postponed', 'cancelled', 'completed', 'abandoned', name='ck_fixtures_status', native_enum=False, length=32), nullable=False),
    sa.Column('our_score', sa.Integer(), nullable=True),
    sa.Column('their_score', sa.Integer(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('player_of_the_match_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'completed') OR (our_score IS NOT NULL AND their_score IS NOT NULL)", name='ck_fixtures_completed_has_score'),
    sa.CheckConstraint('(our_score IS NULL OR our_score >= 0) AND (their_score IS NULL OR their_score >= 0)', name='ck_fixtures_scores_non_negative'),
    sa.ForeignKeyConstraint(['opponent_id'], ['opponents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_of_the_match_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixtures_kickoff_at'), ['kickoff_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_opponent_id'), ['opponent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_fixtures_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_team_id'), ['team_id'], unique=False)

    op.create_table('match_events',
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=True),
    sa.Column('related_player_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('goal', 'own_goal', 'penalty_scored', 'penalty_missed', 'yellow_card', 'second_yellow', 'red_card', 'substitution', name='ck_match_events_type', native_enum=False, length=40), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('added_time', sa.Integer(), nullable=True),
    sa.Column('is_opposition', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_player_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_events_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_events_player_id'), ['player_id'], unique=False)

    op.create_table('player_match_statistics',
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('lineup_role', sa.Enum('starter', 'substitute', 'unused_substitute', name='ck_player_stat_lineup_role', native_enum=False, length=40), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('clean_sheet', sa.Boolean(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('goals >= 0 AND assists >= 0 AND minutes_played >= 0', name='ck_player_stat_non_negative'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'player_id', name='uq_player_stat_fixture_player')
    )
    with op.batch_alter_table('player_match_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_match_statistics_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_statistics_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_match_statistics_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_statistics_fixture_id'))

    op.drop_table('player_match_statistics')
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_events_player_id'))
        batch_op.drop_index(batch_op.f('ix_match_events_fixture_id'))

    op.drop_table('match_events')
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixtures_team_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_status'))
        batch_op.drop_index(batch_op.f('ix_fixtures_slug'))
        batch_op.drop_index(batch_op.f('ix_fixtures_season_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_opponent_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_kickoff_at'))

    op.drop_table('fixtures')
    with op.batch_alter_table('league_standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_standings_season_id'))

    op.drop_table('league_standings')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_slug'))
        batch_op.drop_index(batch_op.f('ix_seasons_competition_id'))

    op.drop_table('seasons')
    with op.batch_alter_table('opponents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opponents_slug'))

    op.drop_table('opponents')
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitions_slug'))

    op.drop_table('competitions')
    # ### end Alembic commands ###
