"""player and staff tables

Revision ID: 46946a13c508
Revises: 733776230a87
Create Date: 2026-09-18 07:38:12.236046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46946a13c508'
down_revision = '733776230a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('known_as', sa.String(length=120), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('squad_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.Enum('goalkeeper', 'defender', 'midfielder', 'forward', name='ck_players_position', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'injured', 'suspended', 'inactive', 'former', name='ck_players_status', native_enum=False, length=32), nullable=False),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=160), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'slug', name='uq_players_team_slug'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)

    op.create_table('staff_members',
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('head_coach', 'assistant_coach', 'goalkeeping_coach', 'team_manager', 'physio', 'official', name='ck_staff_role', native_enum=False, length=40), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_staff_slug')
    )
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_members_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_members_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_staff_members_slug'))

    op.drop_table('staff_members')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_slug'))

    op.drop_table('players')
    # ### end Alembic commands ###
