"""article markdown source

Revision ID: 47c9254390a0
Revises: 3fbc49989d0a
Create Date: 2026-09-25 09:32:32.039164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c9254390a0'
down_revision = '3fbc49989d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_markdown', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('body_markdown')

    # ### end Alembic commands ###
