"""galleries, gallery items, videos and article featured images

Revision ID: d623ce2e73f9
Revises: f9d2ede2745b
Create Date: 2026-09-23 11:54:03.499424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd623ce2e73f9'
down_revision = 'f9d2ede2745b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleries',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('fixture_id', sa.Uuid(), nullable=True),
    sa.Column('cover_asset_id', sa.Uuid(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_galleries_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_galleries_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_galleries_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_galleries_team_id'), ['team_id'], unique=False)

    op.create_table('videos',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('youtube_id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('fixture_id', sa.Uuid(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_videos_team_id'), ['team_id'], unique=False)

    op.create_table('gallery_items',
    sa.Column('gallery_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gallery_id', 'asset_id', name='uq_gallery_items_gallery_asset')
    )
    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_items_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_items_gallery_id'), ['gallery_id'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('articles_featured_image_id_fkey', 'media_assets', ['featured_image_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('articles_featured_image_id_fkey', type_='foreignkey')
        batch_op.drop_column('featured_image_id')

    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_items_gallery_id'))
        batch_op.drop_index(batch_op.f('ix_gallery_items_asset_id'))

    op.drop_table('gallery_items')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_team_id'))
        batch_op.drop_index(batch_op.f('ix_videos_slug'))
        batch_op.drop_index(batch_op.f('ix_videos_is_published'))
        batch_op.drop_index(batch_op.f('ix_videos_fixture_id'))

    op.drop_table('videos')
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_galleries_team_id'))
        batch_op.drop_index(batch_op.f('ix_galleries_slug'))
        batch_op.drop_index(batch_op.f('ix_galleries_is_published'))
        batch_op.drop_index(batch_op.f('ix_galleries_fixture_id'))

    op.drop_table('galleries')
    # ### end Alembic commands ###
