"""club hero image

Revision ID: d9ca4a1616bd
Revises: e7408ee07f27
Create Date: 2026-09-29 09:33:44.140019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ca4a1616bd'
down_revision = 'e7408ee07f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_image_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('clubs_hero_image_id_fkey', 'media_assets', ['hero_image_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('clubs_hero_image_id_fkey', type_='foreignkey')
        batch_op.drop_column('hero_image_id')

    # ### end Alembic commands ###
