"""club values, training times and treasurer role

Revision ID: e7408ee07f27
Revises: 47c9254390a0
Create Date: 2026-09-26 06:40:21.470200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7408ee07f27'
down_revision = '47c9254390a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('values_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('training_times', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('training_times')
        batch_op.drop_column('values_text')

    # ### end Alembic commands ###
