"""social links and support methods

Revision ID: f8cb2cdb51ae
Revises: d623ce2e73f9
Create Date: 2026-09-23 13:22:20.168495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8cb2cdb51ae'
down_revision = 'd623ce2e73f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_links',
    sa.Column('platform', sa.Enum('facebook', 'x', 'instagram', 'youtube', 'tiktok', 'whatsapp', 'linkedin', name='ck_social_links_platform', native_enum=False, length=32), nullable=False),
    sa.Column('url', sa.String(length=400), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', name='uq_social_links_platform')
    )
    op.create_table('support_methods',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('mpesa_paybill', 'mpesa_till', 'mpesa_send_money', 'bank_transfer', 'in_kind', 'other', name='ck_support_methods_kind', native_enum=False, length=40), nullable=False),
    sa.Column('account_label', sa.String(length=60), nullable=True),
    sa.Column('account_value', sa.String(length=60), nullable=True),
    sa.Column('account_name', sa.String(length=160), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_methods')
    op.drop_table('social_links')
    # ### end Alembic commands ###
